name: Deploy Github Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Clean install dependencies
        run: npm ci

      - name: Run unit tests
        if: ${{github.ref_name }} != "refs/heads/main"
        run: "npm run test:unit #"

      - name: Run e2e tests

        uses: browser-actions/setup-chrome@v1
      - run: chrome --version # check chrome version

      - run: sudo apt-get install xvfb # install xfvb
      - run: xvfb-run --auto-servernum npm run test:e2e --headless # run test:e2e through xvfb

      - name: Custom script
        uses: actions/github-script@v6
        with:
          script: |
            console.log({ context });
