name: Deploy Github Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm ci
      - run: "npm run test:unit #"
      - run: npm run test:e2e

      - name: Custom script
        uses: actions/github-script@v6
        with:
          script: |
            console.log({ context });
